In [ ]:
import numpy as np


In [ ]:
lst = [10, 20, 30, 40, 50]
arr = np.array(lst)

print("Array:", arr)
print("Shape:", arr.shape)

Array: [10 20 30 40 50]
Shape: (5,)


In [ ]:
zeros_matrix = np.zeros((3, 5))
ones_matrix = np.ones((2, 5))

print("3x5 Zero Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\n2x5 Ones Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

3x5 Zero Matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Shape: (3, 5)

2x5 Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [ ]:
arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Original Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [ ]:
arr = np.random.randint(1, 100, 10)

print("Array:", arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())

Array: [35 73 90  3 22 76 95  8 16 36]
Minimum: 3
Maximum: 95
Mean: 45.4
Sum: 454


In [ ]:
import pandas as pd

data = {
    "Student Name": ["Aman", "Riya", "Karan", "Neha"],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print(df)
print("\nData Types:\n", df.dtypes)


  Student Name  Marks
0         Aman     85
1         Riya     90
2        Karan     78
3         Neha     88

Data Types:
 Student Name    object
Marks            int64
dtype: object


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sample_data.csv to sample_data.csv


In [ ]:
df = pd.read_csv("sample_data.csv")

print("First Record:\n", df.head(1))
print("\nSecond Record:\n", df.iloc[1])
print("\nLast Record:\n", df.tail(1))

First Record:
    ID   Name  Age  Score Department
0   1  Aarav   20   78.0        CSE

Second Record:
 ID               2
Name          Diya
Age             21
Score         85.0
Department      IT
Name: 1, dtype: object

Last Record:
    ID   Name  Age  Score Department
4   5  Kunal   23   72.0         ME


In [ ]:
df = pd.read_csv("sample_data.csv")

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("\nMissing Values:\n", df.isnull().sum())

Number of Rows: 5
Number of Columns: 5

Missing Values:
 ID            0
Name          0
Age           0
Score         1
Department    0
dtype: int64


In [ ]:
df = pd.read_csv("sample_data.csv")

print("Statistical Summary:\n")
print(df.describe())

Statistical Summary:

             ID       Age      Score
count  5.000000   5.00000   4.000000
mean   3.000000  21.20000  81.250000
std    1.581139   1.30384   7.889867
min    1.000000  20.00000  72.000000
25%    2.000000  20.00000  76.500000
50%    3.000000  21.00000  81.500000
75%    4.000000  22.00000  86.250000
max    5.000000  23.00000  90.000000
